### ISSUE TITLE
Atlassian Cloud: Tracking history shows entries of other users

### ISSUE THREAD

**Issue by BernhardEh** [fochlac/Tempo-Tracker#10]
After switchting to Atlassian Cloud, the tracker doesn't work anymore as before since it shows too many entries in the tracking history.

The tempo app shows it correctly, nevertheless in the plugin I see entries from other users as well:

![image](https://github.com/fochlac/Tempo-Tracker/assets/164212072/5c380f41-7a92-43d7-bf0f-5cd48651bbc3)

![image](https://github.com/fochlac/Tempo-Tracker/assets/164212072/876f6417-8310-4a67-8ae6-32392bdf75f3)

I have configured both API Tokens (Jira and Tempo).

**Comment by fochlac** [comment]
It seems they deprecated the account parameter from the [search](https://apidocs.tempo.io/#tag/Worklogs/operation/searchWorklogs) endpoint I've been using. I've [prepared a fix](https://github.com/fochlac/Tempo-Tracker/pull/11) switching to [getWorklogsByUser](https://apidocs.tempo.io/#tag/Worklogs/operation/getWorklogsByUser) but I cannot really test it since I don't have access to a jira-cloud instance with tempo integration. 

If you could sideload the fixed version and check that everything is working with loading the worklogs I can merge the fix to master and deploy it to the webstores.
![image](https://github.com/fochlac/Tempo-Tracker/assets/19147668/9160be56-573a-4e56-bc14-2e087d78ca2c)
[extension_chrome.zip](https://github.com/user-attachments/files/15994421/extension_chrome.zip)

**Comment by fochlac** [comment]
published as 3.5.3, should be available in the stores soonish.
