### ISSUE TITLE
Aggregated working-time in Workday differs from aggregated working-time in Jira

### ISSUE THREAD

**Issue by mlrdev** [fochlac/Tempo-Tracker#8]
Hi @fochlac,
after using your great plugin for a while now, including the new functionality for pushing the recorded worklog into workday, I saw a discrepancy betrween the aggregates visible in Jira and the aggregates visible in Workday. See the attached screenshot.

![collage](https://github.com/fochlac/Tempo-Tracker/assets/8323838/273c132c-e752-4fb4-b678-a6aceae39444)

I have the feeling, that the correction of the intervals before uploading them to Workday might add to this behavior, as the difference seems bigger to me on days where there have been more topics compared to days where there was less (but I could be wrong).

Regards,

**Comment by fochlac** [comment]
this is caused by an issue of the workday api.
If a worklog exists from 10:15-10:45 a new worklog from 9:45-10:15 will be rejected. 
If the worklog from 9:45 - 10:15 is inserted first though, it will work. To work around this each worklog's start time is rounded up and its end-time is rounded down.
Ideally the upload should be able to delete existing entries if a possible conflict is detected, so this rounding is not needed.

To fix this multiple steps are required:
- [ ] extract information about uploaded/approved time slots
- [ ] autoselect all non-uploaded worktime segments
- [ ] add possibility to delete worktime slots
- [ ] detect conflicts, and fix them if needed. possibly remove and recreate worklogs not part of the upload sequence
- [ ] add sync all-button

**Comment by fochlac** [comment]
The api has partial support for exact times - it accepts start/end-times including seconds and persists exact times, but will only expose full minutes. This had to be considered for the collision detection alogrithm, but allowed me to round to seconds instead.
Loosing a few seconds each day seems more acceptable, compared to loosing a few minutes each day, so I won't implement delete for workday times.
